### ISSUE TITLE
Excess Padding (Top & Bottom) on API 18 [Jelly Bean]

### ISSUE THREAD

**Issue by ThunderRoid** [fiskurgit/ChipCloud#5] opened 2016-07-03 17:39 UTC
Excess Padding (Top or Bottom) on API 18 [Jelly Bean], as you can the padding looks great on API 21 but on 18, it looks odd. 
Sorry if I am annoying you.
Thank you again so much for creating such a great library.

API 21
![good](https://cloud.githubusercontent.com/assets/3328263/16546777/39190454-4177-11e6-9b6e-9b0b036bdc74.png)

API 18
![bad](https://cloud.githubusercontent.com/assets/3328263/16546770/06121bb8-4177-11e6-8995-e55bebb03120.png)

**Comment by fiskurgit** [comment] 2016-07-03 17:52
Ha, don't worry, I suspect it's another compat issue. I'll look at it sometime in the next few days.

**Comment by fiskurgit** [comment] 2016-07-04 08:30
<img width="339" alt="screen shot 2016-07-04 at 09 28 25" src="https://cloud.githubusercontent.com/assets/5167046/16554899/b76f7f66-41c9-11e6-9b12-e293be100be2.png">

Can't replicate the issue in a Jelly Bean emulator, are you seeing the problem on a device, or in the emu? Could you try creating a simple Activity with nothing but the ChipCloud in a layout and see if the same issue occurs.

**Comment by ThunderRoid** [comment] 2016-07-04 12:20
```java
public class MainActivity extends AppCompatActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        String[] mClips = new String[]{"Google Play", "Apple Music", "Billboard", "Spotify", "Pandora", "Last.fm"};
        final ChipCloud chipCloud = (ChipCloud) findViewById(R.id.chip_cloud);
        new ChipCloud.Configure()
                .chipCloud(chipCloud)
                .selectedColor(getResources().getColor(R.color.colorAccent))
                .chipListener(new ChipListener() {
                    @Override
                    public void chipSelected(int index) {
                    }

                    @Override
                    public void chipDeselected(int index) {
                    }
                }).build();

        for (String clip : mClips) {
            chipCloud.addChip(clip);
        }
        chipCloud.setSelectedChip(0);
    }
}
```



```xml
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:chipcloud="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:paddingBottom="@dimen/activity_vertical_margin"
    android:paddingTop="@dimen/activity_vertical_margin"
    android:layout_height="match_parent"
    tools:context="com.myapplication.MainActivity">

    <eu.fiskur.chipcloud.ChipCloud
        android:id="@+id/chip_cloud"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginEnd="@dimen/margin_full"
        android:layout_marginLeft="@dimen/margin_full"
        android:layout_marginRight="@dimen/margin_full"
        android:layout_marginStart="@dimen/margin_full"
        chipcloud:deselectTransitionMS="500"
        chipcloud:selectTransitionMS="750" />
</RelativeLayout>
```

Screenshot from official Android Jelly Bean Emulator
![err](https://cloud.githubusercontent.com/assets/3328263/16560140/4d290178-4213-11e6-9533-7ea6c07128dd.png)

![err2](https://cloud.githubusercontent.com/assets/3328263/16560247/029d1a58-4214-11e6-8111-e1caa8c2b9f3.png)

**Comment by fiskurgit** [comment] 2016-07-04 12:27
Perfect thanks. May be the margins in the XML, will get on it.

**Comment by fiskurgit** [comment] 2016-07-04 14:10
<img width="359" alt="screen shot 2016-07-04 at 14 50 56" src="https://cloud.githubusercontent.com/assets/5167046/16562841/c03af1f2-41f6-11e6-95bb-57f289e98cb0.png">

k, managed to replicate it - the issue isn't the OS version, but the screen density and some magic numbers for layoutparams in the old FlowLayout class, have replaced that with a dp to pixel calculation so the layout will look the same across all screen densities: https://github.com/fiskurgit/ChipCloud/commit/79aa384863c5e679cee07bb4126c9115a09f6d0e#diff-0f9f7eb079394317b6ed798890e1cc34

Should be fixed in **2.0.6** - let me know if it's still problematic and I'll reopen this ticket. 

In the next release I'll also add a method and xml attribute to control the layoutparams so the implementation can control the chip spacing. And also another simple method so you can pass a string[] instead of iterating yourself like in your example above.

**Closed by fiskurgit** 2016-07-04 14:10 UTC
Labels: bug

**Comment by ThunderRoid** [comment] 2016-07-04 18:43
Thanks so much. BTW, is it possible to add another method such that the user cannot deselect a clip. User can select another cilp but one clip must be selected at all times. Just like radio button group behaviour. Once a button is selected, user can only deselect it by selecting another button. And clicking on selected button will not deselect it.
Thanks again.

**Comment by fiskurgit** [comment] 2016-07-04 18:58
No worries - and yeah, that'd be a sensible addition so will add it over the next few days at some point, will require removing the singleChoice syntax and replacing it with support for 3 states (Single Choice, Multi-choice, and the new 'Required' choice mode)

**Comment by fiskurgit** [comment] 2016-07-05 10:23
@ThunderRoid Have just released **2.1.0** - there's a lot of changes so let me know if you find any glitches. Full details in the [readme example code](https://github.com/fiskurgit/ChipCloud/blob/master/README.md). I've added methods to set a string[], and if your array exists in xml resources you can set it in the xml layout which is really nice, plus you can set the new 'required' mode this way too:

```xml
<eu.fiskur.chipcloud.ChipCloud
    xmlns:chipcloud="http://schemas.android.com/apk/res-auto"
    android:id="@+id/chip_cloud"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    chipcloud:labels="@array/labels"
    chipcloud:selectMode="required"/>
```

As mentioned above introducing a 3rd mode has meant I've removed singleChoice entirely, there's now an enum of choices instead:

```java
  public enum Mode {
    SINGLE, MULTI, REQUIRED
  }
```

The library is in a much better shape thanks to your feedback, cheers

**Comment by ThunderRoid** [comment] 2016-07-05 13:13
Thanks so much for this update.

NOTE: when mode is set to REQUIRED, after selecting a clip, if I tap on it again, nothing happens, but if I tap again (2nd time) on the same selected clip, "chipSelected" is called again plus you see a deselectTransitionMS & selectTransitionMS.

**Comment by fiskurgit** [comment] 2016-07-05 13:26
yeah - saw that too, will live with it for now, may come back to that in the future.
